### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by mytk2012** [jysung/activity_detection#8]
Can you offer me CAD-120 dataset?Official link is invalid，please leave your google drive when convenient.

**Comment by jysung** [comment]
This is only for CAD-60 dataset. For CAD-120, please contact Hema Koppula (http://www.cs.cornell.edu/~hema/)
For CAD-60 dataset, please email me.

**Comment by mytk2012** [comment]
I cannot reach the link as you recommed.It seems the link(http://pr.cs.cornell.edu/humanactivities/data.php) has been avoided,can you help me contact and get CAD-120 dataset?Best
 wishes!
